version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Every test should be fully mocked, or fail.
      # This remove network conenctivity to the domains used for communicating with the API
      # Also note that the test environment doesn't have a valid API key in environment
      - run: echo 127.0.0.1 ddragon.leagueoflegends.com | sudo tee -a /etc/hosts
      - run: echo 127.0.0.1 euw.api.riotgames.com | sudo tee -a /etc/hosts
      - run: echo 127.0.0.1 na.api.riotgames.com | sudo tee -a /etc/hosts
      - run: npm test
      - run: npm run lint
      # Run tests again, but this time display them in the output
      - run:
          name: Coverage & junit
          command: npm run coverage
          environment:
            MOCHA_REPORTER: mocha-junit-reporter
            MOCHA_FILE: /tmp/junit-test-results.xml
      - store_artifacts:
          path: ./coverage
          destination: coverage
      - store_test_results:
          path: /tmp/junit-test-results.xml
